name: Build and Deploy
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Create Config File
        run: |
          echo "window.YOLUKO_CONFIG = {" > config.js
          echo "  formspreeId: '${{ secrets.FORMSPREE_ID }}'," >> config.js
          echo "  ga4Id: '${{ secrets.GA4_ID }}'" >> config.js
          echo "};" >> config.js
      
      - name: Remove Beefree References
        run: |
          # Remove Beefree footer and references in index.html
          sed -i '/Designed with Beefree/d' index.html
          sed -i '/designedwithbeefree/d' index.html
          sed -i '/<div class="bee-row bee-row-35">/,/<\/div><\/div><\/div>/d' index.html
          
          # Remove Beefree footer and references in fr/index.html
          sed -i '/Designed with Beefree/d' fr/index.html
          sed -i '/designedwithbeefree/d' fr/index.html
          sed -i '/<div class="bee-row bee-row-35">/,/<\/div><\/div><\/div>/d' fr/index.html
          
          # Remove any other Beefree links or references
          sed -i 's/beepro-thumbnail\.getbee\.io/yoluko.com/g' index.html
          sed -i 's/beepro-thumbnail\.getbee\.io/yoluko.com/g' fr/index.html
          sed -i 's/d1oco4z2z1fhwp\.cloudfront\.net\/assets\/Beefree-logo\.png//g' index.html
          sed -i 's/d1oco4z2z1fhwp\.cloudfront\.net\/assets\/Beefree-logo\.png//g' fr/index.html
      
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./